name: 'Bot auto-{approve,merge}'

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: yettoapp/actions/.github/workflows/automerge_dependabot.yml@main
    secrets: inherit
    with: 
      automerge: true

  sisyphusbot:
    uses: yettoapp/actions/.github/workflows/automerge_sisyphusbot.yml@main
    secrets: inherit
